version: '3'
services:
  api:
    build: .
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - db_volume:/var/lib/mongodb
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
volumes:
  db_volume:
    external: true
