version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
  frontend:
    build: ./frontend
    depends_on:
      - api
  db:
    image: mongo:latest
    volumes:
      - db_volume:/var/lib/mongodb
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
volumes:
  db_volume:
    external: true
